# Generated by Django 5.2.11 on 2026-03-04 03:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=10)),
                ('model', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DosenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nama', models.CharField(max_length=120)),
                ('nidn', models.CharField(max_length=50, unique=True)),
                ('jabatan', models.CharField(blank=True, max_length=120)),
                ('prodi', models.CharField(blank=True, max_length=120)),
                ('fakultas', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_dosen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dosen',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DokumenTriDharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file_checksum', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('kategori', models.CharField(choices=[('pengajaran', 'Pengajaran'), ('penelitian', 'Penelitian'), ('pengabdian', 'Pengabdian'), ('penunjang', 'Penunjang')], db_index=True, max_length=20)),
                ('tahun', models.PositiveIntegerField(db_index=True)),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap'), ('antara', 'Antara')], db_index=True, default='ganjil', max_length=10)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('jenis_bukti', models.CharField(help_text='Contoh: RPS, Kontrak Kuliah, Jurnal, Sertifikat, SK, Laporan', max_length=120)),
                ('kode_standar', models.CharField(blank=True, help_text='Opsional: kode/standar borang/indikator akreditasi.', max_length=50)),
                ('kata_kunci', models.CharField(blank=True, help_text='Pisahkan dengan koma. Contoh: rps, OBE, rubrik', max_length=250)),
                ('file_bukti', models.FileField(upload_to='akreditasi/dokumen/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'png', 'jpg', 'jpeg', 'zip'])])),
                ('tautan', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], db_index=True, default='draft', max_length=20)),
                ('rejected_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_tridharma_diajukan', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_tridharma_diverifikasi', to=settings.AUTH_USER_MODEL)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_tridharma', to='dosen.dosenprofile')),
            ],
            options={
                'verbose_name_plural': 'Dokumen Tri Dharma',
                'ordering': ['-tahun', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KelasKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tahun_ajaran', models.CharField(help_text='Contoh: 2025/2026', max_length=30)),
                ('nama_kelas', models.CharField(help_text='Contoh: A / B / Reg / Ekstensi', max_length=50)),
                ('dosen_pengampu', models.ManyToManyField(related_name='kelas_diampu', to='dosen.dosenprofile')),
            ],
            options={
                'verbose_name_plural': 'Kelas Kuliah',
                'ordering': ['-tahun_ajaran', 'mata_kuliah__kode', 'nama_kelas'],
            },
        ),
        migrations.CreateModel(
            name='LuaranMataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('allowed_ext', models.CharField(default='pdf,doc,docx,ppt,pptx,zip,rar', help_text='Daftar ekstensi yang diizinkan (dipisah koma).', max_length=200)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luaran', to='dosen.kelaskuliah')),
            ],
            options={
                'verbose_name_plural': 'Luaran Mata Kuliah',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MahasiswaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nama', models.CharField(max_length=120)),
                ('nim', models.CharField(max_length=50, unique=True)),
                ('prodi', models.CharField(blank=True, max_length=120)),
                ('angkatan', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kode', models.CharField(db_index=True, max_length=30)),
                ('nama', models.CharField(max_length=200)),
                ('prodi', models.CharField(blank=True, max_length=120)),
                ('semester', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Mata Kuliah',
                'ordering': ['kode'],
                'unique_together': {('kode', 'prodi')},
            },
        ),
        migrations.AddField(
            model_name='kelaskuliah',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='dosen.matakuliah'),
        ),
        migrations.CreateModel(
            name='PengajuanBimbingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('jenis', models.CharField(choices=[('pa', 'Bimbingan Akademik (Dosen PA)'), ('skripsi', 'Bimbingan Skripsi')], default='pa', max_length=20)),
                ('topik', models.CharField(blank=True, max_length=200)),
                ('pesan', models.TextField(help_text='Jelaskan kebutuhan bimbingan / pertanyaan utama.')),
                ('usulan_waktu', models.DateTimeField(blank=True, help_text='Usulan jadwal dari mahasiswa (opsional).', null=True)),
                ('jadwal_disetujui', models.DateTimeField(blank=True, help_text='Jadwal bimbingan yang disepakati.', null=True)),
                ('metode', models.CharField(choices=[('offline', 'Tatap Muka'), ('online', 'Online')], default='offline', max_length=20)),
                ('lokasi_or_link', models.CharField(blank=True, help_text='Ruang kelas/gedung atau link meeting.', max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Diajukan'), ('approved', 'Disetujui / Dijadwalkan'), ('rejected', 'Ditolak'), ('done', 'Selesai'), ('canceled', 'Dibatalkan')], db_index=True, default='submitted', max_length=20)),
                ('rejected_reason', models.TextField(blank=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_bimbingan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('dosen_pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_masuk', to='dosen.dosenprofile')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_bimbingan', to='dosen.mahasiswaprofile')),
            ],
            options={
                'verbose_name_plural': 'Pengajuan Bimbingan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatatanBimbingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file_checksum', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('tanggal_pertemuan', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ringkasan', models.TextField(help_text='Ringkasan diskusi / hasil bimbingan.')),
                ('tindak_lanjut', models.TextField(blank=True, help_text='Action items / tugas lanjutan.')),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='bimbingan/lampiran/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'])])),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catatan_bimbingan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='dosen.pengajuanbimbingan')),
            ],
            options={
                'verbose_name_plural': 'Log Catatan Bimbingan',
                'ordering': ['-tanggal_pertemuan'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLuaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file_checksum', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('file_karya', models.FileField(upload_to='portofolio/submission/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip', 'rar'])])),
                ('catatan_mahasiswa', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Dikirim'), ('revision', 'Perlu Revisi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], db_index=True, default='submitted', max_length=20)),
                ('feedback_dosen', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('luaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dosen.luaranmatakuliah')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dosen.mahasiswaprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Submission Luaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dosenprofile',
            index=models.Index(fields=['nidn'], name='dosen_dosen_nidn_11085d_idx'),
        ),
        migrations.AddIndex(
            model_name='dosenprofile',
            index=models.Index(fields=['nama'], name='dosen_dosen_nama_606c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='dosenprofile',
            index=models.Index(fields=['prodi'], name='dosen_dosen_prodi_86f7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumentridharma',
            index=models.Index(fields=['tahun', 'semester'], name='dosen_dokum_tahun_e49fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='dokumentridharma',
            index=models.Index(fields=['status'], name='dosen_dokum_status_fb0177_idx'),
        ),
        migrations.AddIndex(
            model_name='mahasiswaprofile',
            index=models.Index(fields=['nim'], name='dosen_mahas_nim_b8ada8_idx'),
        ),
        migrations.AddIndex(
            model_name='mahasiswaprofile',
            index=models.Index(fields=['nama'], name='dosen_mahas_nama_05ae22_idx'),
        ),
        migrations.AddIndex(
            model_name='mahasiswaprofile',
            index=models.Index(fields=['prodi'], name='dosen_mahas_prodi_1b374e_idx'),
        ),
        migrations.AddIndex(
            model_name='pengajuanbimbingan',
            index=models.Index(fields=['status'], name='dosen_penga_status_db6289_idx'),
        ),
        migrations.AddIndex(
            model_name='pengajuanbimbingan',
            index=models.Index(fields=['jenis'], name='dosen_penga_jenis_af6de6_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionluaran',
            index=models.Index(fields=['status'], name='dosen_submi_status_5329d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionluaran',
            unique_together={('luaran', 'mahasiswa')},
        ),
    ]
