# Generated by Django 5.2.11 on 2026-03-05 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dosen.kelaskuliah')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dosen.mahasiswaprofile')),
            ],
            options={
                'verbose_name_plural': 'Peserta Kelas',
                'indexes': [models.Index(fields=['kelas', 'is_active'], name='dosen_enrol_kelas_i_a216f6_idx'), models.Index(fields=['mahasiswa', 'is_active'], name='dosen_enrol_mahasis_a449a4_idx')],
                'unique_together': {('kelas', 'mahasiswa')},
            },
        ),
    ]
