# Generated by Django 5.2.11 on 2026-03-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0003_chatthreadbimbingan_chatmessagebimbingan'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='sks',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='NilaiMataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tahun_ajaran', models.CharField(db_index=True, max_length=30)),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], db_index=True, max_length=10)),
                ('nilai', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_index=True, max_length=2)),
                ('sks_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='dosen.mahasiswaprofile')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_mahasiswa', to='dosen.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Nilai Mata Kuliah',
                'indexes': [models.Index(fields=['tahun_ajaran', 'semester'], name='dosen_nilai_tahun_a_440955_idx'), models.Index(fields=['nilai'], name='dosen_nilai_nilai_f5212a_idx')],
                'unique_together': {('mahasiswa', 'mata_kuliah', 'tahun_ajaran', 'semester')},
            },
        ),
    ]
