# Generated by Django 5.2.11 on 2026-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0004_matakuliah_sks_nilaimatakuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosenprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mahasiswaprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
